apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebi-assignment
spec:
  selector:
    matchLabels:
      app: ebi-assignment
  replicas: 2 
  template:
    metadata:
      labels:
        app: ebi-assignment
    spec:
      containers:
      - name: ebi-assignment
        image: ebiassignmenttask/ebi-assignment-task:latest
        ports:
        - containerPort: 2020

---
# Node Port Service 
apiVersion: v1
kind: Service
metadata:
  name: ebi-assignment
spec:
  type: NodePort
  ports:
    - port: 2020
      targetPort: 2020
  selector:
    app: ebi-assignment