apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-docker
spec:
  selector:
    matchLabels:
      app: jenkins-docker
  replicas: 2 
  template:
    metadata:
      labels:
        app: jenkins-docker
    spec:
      containers:
      - name: simple-service
        image: devopstrika/docker-jenkins-image:latest
        ports:
        - containerPort: 8080

---
# Node Port Service 
apiVersion: v1
kind: Service
metadata:
  name: jenkins-docker
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins-docker